name: boutique
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  data_table_2: ^2.2.1
  syncfusion_flutter_datagrid: ^19.4.56
  flutter_barcode_listener: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
